--
-- PostgreSQL database dump
--

-- Dumped from database version 12.22 (Ubuntu 12.22-0ubuntu0.20.04.4)
-- Dumped by pg_dump version 12.22 (Ubuntu 12.22-0ubuntu0.20.04.4)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP DATABASE number_guess;
--
-- Name: number_guess; Type: DATABASE; Schema: -; Owner: freecodecamp
--

CREATE DATABASE number_guess WITH TEMPLATE = template0 ENCODING = 'UTF8' LC_COLLATE = 'C.UTF-8' LC_CTYPE = 'C.UTF-8';


ALTER DATABASE number_guess OWNER TO freecodecamp;

\connect number_guess

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: games; Type: TABLE; Schema: public; Owner: freecodecamp
--

CREATE TABLE public.games (
    game_id integer NOT NULL,
    user_id integer NOT NULL,
    number_of_guesses integer NOT NULL,
    secret_number integer NOT NULL,
    played_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.games OWNER TO freecodecamp;

--
-- Name: games_game_id_seq; Type: SEQUENCE; Schema: public; Owner: freecodecamp
--

ALTER TABLE public.games ALTER COLUMN game_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.games_game_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usernames; Type: TABLE; Schema: public; Owner: freecodecamp
--

CREATE TABLE public.usernames (
    user_id integer NOT NULL,
    username character varying(22) NOT NULL
);


ALTER TABLE public.usernames OWNER TO freecodecamp;

--
-- Name: usernames_user_id_seq; Type: SEQUENCE; Schema: public; Owner: freecodecamp
--

ALTER TABLE public.usernames ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usernames_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: games; Type: TABLE DATA; Schema: public; Owner: freecodecamp
--

INSERT INTO public.games VALUES (71, 162, 0, 1, '2026-01-19 22:02:38.846527');
INSERT INTO public.games VALUES (72, 162, 0, 1, '2026-01-19 22:02:39.114172');
INSERT INTO public.games VALUES (73, 164, 0, 1, '2026-01-19 22:02:39.488892');
INSERT INTO public.games VALUES (74, 164, 0, 1, '2026-01-19 22:02:39.723348');
INSERT INTO public.games VALUES (75, 162, 0, 1, '2026-01-19 22:02:40.048254');
INSERT INTO public.games VALUES (76, 162, 0, 1, '2026-01-19 22:02:40.380425');
INSERT INTO public.games VALUES (77, 162, 0, 1, '2026-01-19 22:02:40.932686');
INSERT INTO public.games VALUES (78, 169, 0, 1, '2026-01-19 22:02:48.574064');
INSERT INTO public.games VALUES (79, 169, 0, 1, '2026-01-19 22:02:48.80773');
INSERT INTO public.games VALUES (80, 171, 0, 1, '2026-01-19 22:02:49.040861');
INSERT INTO public.games VALUES (81, 171, 0, 1, '2026-01-19 22:02:49.278077');
INSERT INTO public.games VALUES (82, 169, 0, 1, '2026-01-19 22:02:49.510286');
INSERT INTO public.games VALUES (83, 169, 0, 1, '2026-01-19 22:02:49.969519');
INSERT INTO public.games VALUES (84, 169, 0, 1, '2026-01-19 22:02:50.293858');
INSERT INTO public.games VALUES (85, 176, 11, 412, '2026-01-19 22:04:03.96295');
INSERT INTO public.games VALUES (86, 177, 825, 824, '2026-01-19 22:04:09.496857');
INSERT INTO public.games VALUES (87, 177, 798, 797, '2026-01-19 22:04:09.810871');
INSERT INTO public.games VALUES (88, 178, 933, 932, '2026-01-19 22:04:10.073447');
INSERT INTO public.games VALUES (89, 178, 435, 434, '2026-01-19 22:04:10.354993');
INSERT INTO public.games VALUES (90, 177, 169, 166, '2026-01-19 22:04:10.602698');
INSERT INTO public.games VALUES (91, 177, 519, 518, '2026-01-19 22:04:10.878686');
INSERT INTO public.games VALUES (92, 177, 917, 916, '2026-01-19 22:04:11.198859');
INSERT INTO public.games VALUES (93, 179, 198, 197, '2026-01-19 22:04:26.361359');
INSERT INTO public.games VALUES (94, 179, 663, 662, '2026-01-19 22:04:26.654564');
INSERT INTO public.games VALUES (95, 180, 716, 715, '2026-01-19 22:04:26.905539');
INSERT INTO public.games VALUES (96, 180, 911, 910, '2026-01-19 22:04:27.20761');
INSERT INTO public.games VALUES (97, 179, 874, 871, '2026-01-19 22:04:27.527301');
INSERT INTO public.games VALUES (98, 179, 933, 932, '2026-01-19 22:04:27.825362');
INSERT INTO public.games VALUES (99, 179, 187, 186, '2026-01-19 22:04:28.07732');
INSERT INTO public.games VALUES (100, 181, 94, 93, '2026-01-19 22:20:19.812083');
INSERT INTO public.games VALUES (101, 181, 807, 806, '2026-01-19 22:20:20.116164');
INSERT INTO public.games VALUES (102, 182, 825, 824, '2026-01-19 22:20:20.375708');
INSERT INTO public.games VALUES (103, 182, 961, 960, '2026-01-19 22:20:20.773171');
INSERT INTO public.games VALUES (104, 181, 970, 967, '2026-01-19 22:20:21.142098');
INSERT INTO public.games VALUES (105, 181, 868, 867, '2026-01-19 22:20:21.461155');
INSERT INTO public.games VALUES (106, 181, 919, 918, '2026-01-19 22:20:21.757334');
INSERT INTO public.games VALUES (107, 183, 958, 957, '2026-01-19 22:21:07.285263');
INSERT INTO public.games VALUES (108, 183, 299, 298, '2026-01-19 22:21:07.542593');
INSERT INTO public.games VALUES (109, 184, 186, 185, '2026-01-19 22:21:07.742231');
INSERT INTO public.games VALUES (110, 184, 683, 682, '2026-01-19 22:21:08.030384');
INSERT INTO public.games VALUES (111, 183, 486, 483, '2026-01-19 22:21:08.320203');
INSERT INTO public.games VALUES (112, 183, 165, 164, '2026-01-19 22:21:08.557796');
INSERT INTO public.games VALUES (113, 183, 845, 844, '2026-01-19 22:21:08.857998');
INSERT INTO public.games VALUES (114, 185, 628, 627, '2026-01-19 22:22:47.04402');
INSERT INTO public.games VALUES (115, 185, 153, 152, '2026-01-19 22:22:47.354089');
INSERT INTO public.games VALUES (116, 186, 454, 453, '2026-01-19 22:22:47.603441');
INSERT INTO public.games VALUES (117, 186, 768, 767, '2026-01-19 22:22:47.89663');
INSERT INTO public.games VALUES (118, 185, 525, 522, '2026-01-19 22:22:48.190309');
INSERT INTO public.games VALUES (119, 185, 365, 364, '2026-01-19 22:22:48.447708');
INSERT INTO public.games VALUES (120, 185, 436, 435, '2026-01-19 22:22:48.707812');


--
-- Data for Name: usernames; Type: TABLE DATA; Schema: public; Owner: freecodecamp
--

INSERT INTO public.usernames VALUES (162, 'user_1768878158451');
INSERT INTO public.usernames VALUES (164, 'user_1768878158450');
INSERT INTO public.usernames VALUES (169, 'user_1768878168088');
INSERT INTO public.usernames VALUES (171, 'user_1768878168087');
INSERT INTO public.usernames VALUES (176, 't1');
INSERT INTO public.usernames VALUES (177, 'user_1768878249214');
INSERT INTO public.usernames VALUES (178, 'user_1768878249213');
INSERT INTO public.usernames VALUES (179, 'user_1768878266102');
INSERT INTO public.usernames VALUES (180, 'user_1768878266101');
INSERT INTO public.usernames VALUES (181, 'user_1768879219600');
INSERT INTO public.usernames VALUES (182, 'user_1768879219599');
INSERT INTO public.usernames VALUES (183, 'user_1768879266981');
INSERT INTO public.usernames VALUES (184, 'user_1768879266980');
INSERT INTO public.usernames VALUES (185, 'user_1768879366752');
INSERT INTO public.usernames VALUES (186, 'user_1768879366751');


--
-- Name: games_game_id_seq; Type: SEQUENCE SET; Schema: public; Owner: freecodecamp
--

SELECT pg_catalog.setval('public.games_game_id_seq', 120, true);


--
-- Name: usernames_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: freecodecamp
--

SELECT pg_catalog.setval('public.usernames_user_id_seq', 186, true);


--
-- Name: games games_pkey; Type: CONSTRAINT; Schema: public; Owner: freecodecamp
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_pkey PRIMARY KEY (game_id);


--
-- Name: usernames usernames_pkey; Type: CONSTRAINT; Schema: public; Owner: freecodecamp
--

ALTER TABLE ONLY public.usernames
    ADD CONSTRAINT usernames_pkey PRIMARY KEY (user_id);


--
-- Name: usernames usernames_username_key; Type: CONSTRAINT; Schema: public; Owner: freecodecamp
--

ALTER TABLE ONLY public.usernames
    ADD CONSTRAINT usernames_username_key UNIQUE (username);


--
-- Name: games_user_id_idx; Type: INDEX; Schema: public; Owner: freecodecamp
--

CREATE INDEX games_user_id_idx ON public.games USING btree (user_id);


--
-- Name: games games_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: freecodecamp
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.usernames(user_id);


--
-- PostgreSQL database dump complete
--

